name: Typescript-build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4.4.0
      with:
        node-version: 18
        cache: 'npm'
    - run: npm install
    - name: Test
      run: npm test

